export const FETCH_HOME_ORDERS_LIST='FETCH_HOME_ORDERS_LIST'

export const FETCH_RELEVENT_ORDERS_LIST='FETCH_RELEVENT_ORDERS_LIST'
export const FETCH_POSTED_ORDER_LIST='FETCH_POSTED_ORDER_LIST'
export const FETCH_PROCESSING_ORDERS_LIST='FETCH_PROCESSING_ORDERS_LIST'
export const FETCH_DELIVERY_ORDERS_LIST='FETCH_DELIVERY_ORDERS_LIST'


export const FETCH_MY_CREATED_ORDERS_LIST='FETCH_MY_CREATED_ORDERS_LIST'

export const FETCH_ECHO="FETCH_ECHO"



export const FETCH_PUBLIC_USER_PROFILE="FETCH_PUBLIC_USER_PROFILE"
export const FETCH_POSTED_ORDERS_LOCAL_AND_INTERNATIONAL_LIST="FETCH_POSTED_ORDERS_LOCAL_AND_INTERNATIONAL_LIST"
export const FETCH_INTERNATIONAL_POSTED_ORDERS_LIST="FETCH_INTERNATIONAL_POSTED_ORDERS_LIST"
export const FETCH_HEIGH_PAID_ORDERS_LIST="FETCH_HEIGH_PAID_ORDERS_LIST"
export const FETCH_HEIGH_PAID_ORDERS_LIST_BY_CITY="FETCH_HEIGH_PAID_ORDERS_LIST_BY_CITY"
export const FETCH_ALL_INTERNATIONAL_POSTED_ORDERS_LIST="FETCH_ALL_INTERNATIONAL_POSTED_ORDERS_LIST"
export const FETCH_LOCAL_POSTED_ORDERS_LIST="FETCH_LOCAL_POSTED_ORDERS_LIST"

export const FETCH_ORDER_OFFERS_REQUESTS_LIST="FETCH_ORDER_OFFERS_REQUESTS_LIST"
export const FETCH_SINGLE_ORDER_OFFERS_REQUEST_DETAILS="FETCH_SINGLE_ORDER_OFFERS_REQUEST_DETAILS"

export const FETCH_ORDER_HISTORY_LIST="FETCH_ORDER_HISTORY_LIST"
export const FETCH_ORDER_DELIVERY_HISTORY_LIST="FETCH_ORDER_DELIVERY_HISTORY_LIST"
export const FETCH_DISPUTED_ORDERS_LIST="FETCH_DISPUTED_ORDERS_LIST"

export const FETCH_DELIVERY_HISTORY_ORDER_DETAILS="FETCH_DELIVERY_HISTORY_ORDER_DETAILS"

export const FETCH_POPULAR_STORES_LIST="FETCH_POPULAR_STORES_LIST"

export const FETCH_OTP="FETCH_OTP"

export const FETCH_WALLET_HISTORY_LIST="FETCH_WALLET_HISTORY_LIST"
export const FETCH_WALLET_DELIVERY_DETAILS="FETCH_WALLET_DELIVERY_DETAILS"
export const FETCH_WALLET_PAYOUT_DETAILT="FETCH_WALLET_PAYOUT_DETAILT"
export const FETCH_WALLET_REFUND_DETAILS="FETCH_WALLET_REFUND_DETAILS"
//starting api
export const SET_USER_INFO="SET_USER_INFO"
export const SET_PUBLIC_USER_INFO="SET_PUBLIC_USER_INFO"
export const SET_GUEST="SET_GUEST"
export const SET_LOGOUT="SET_LOGOUT"


export const FETCH_COUNTRIES_LIST = "FETCH_COUNTRIES_LIST"
export const FETCH_SHOP_ADDRESS = "FETCH_SHOP_ADDRESS"
export const FETCH_DELIVERY_ADDRESS = "FETCH_DELIVERY_ADDRESS"

//filter orders with radius
export const FILTER_ORDERS_RADIUS="FILTER_ORDERS_RADIUS"
//filter orders
export const FILTER_ORDERS="FILTER_ORDERS"
export const SET_LOCAL_FILTER="SET_LOCAL_FILTER"
export const SET_CLEAR_LOCAL_FILTER="SET_CLEAR_LOCAL_FILTER"
export const SET_INTERNATIONAL_FILTER="SET_INTERNATIONAL_FILTER"
export const SET_CLEAR_INTERNATIONAL_FILTER="SET_CLEAR_INTERNATIONAL_FILTER"

//
export const FETCH_LANGUAGE="FETCH_LANGUAGE"

export const FETCH_MY_OFFERS_LIST="FETCH_MY_OFFERS_LIST"


export const FETCH_INBOX_LIST="FETCH_INBOX_LIST"
export const OPEN_ACTIVE_THREAD_CHAT="OPEN_ACTIVE_THREAD_CHAT"
export const SET_LAST_SEEN="SET_LAST_SEEN"
export const UPDATE_ACTIVE_THREAD_CHAT="UPDATE_ACTIVE_THREAD_CHAT"

export const UPDATE_DEFAULT_COUNTRY='UPDATE_DEFAULT_COUNTRY'
//delivery address modal
export const DELIVERY_ADDRESS='DELIVERY_ADDRESS'
export const TOGGLE_DELIVERY_ADDREES_MODAL='TOGGLE_DELIVERY_ADDREES_MODAL'


export const FETCH_NOTIFICATIONS='FETCH_NOTIFICATIONS'

