const onBoardContentList = [
  { title: "Welcome to Taketo", content: `The world’s largest\nShopping & Travel Community.` },
  { title: "Turn Notifications\n&Location Services", content: `From games to gadgets, get any product from\nabroad, delivered by travelers.` },
  { title: "Shop from abroad", content: `From games to gadgets, get any product from\nabroad, delivered by travelers.` },
  { title: "Make money traveling", content: "Make money every time you travel, by delivering\nproducts to locals along the way." },
];
const conversation = [
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-13T11:20:35.069Z", counter: "3" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-12T06:20:36.069Z", counter: "2" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-10T06:20:37.069Z", counter: "5" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-11T06:20:38.069Z", counter: "10" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-07T06:20:39.069Z", counter: "34" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-14T06:20:31.069Z", counter: "1" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-16T06:20:32.069Z", counter: "0" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-13T06:20:33.069Z", counter: "3" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-09T06:20:34.069Z", counter: "5" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-10T06:20:41.069Z", counter: "8" },
  { name: "Zenab Thaqi", message: "Can you please approve", time: "2021-11-11T06:20:42.069Z", counter: "9" },
  { name: "Zenab Thaqi", message: "last", time: "2021-11-15T06:20:43.069Z", counter: "3" },
];

const home_orders_list = {
  data: {
    relevant_orders: [
      {
        order_id: "89976",
        order_title: "fuga et eum",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://paul.name",
        order_price: "486.59",
        order_reward_price: "889.11",
        order_from: "Saint Helena",
        order_to: "Albania",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Mon Jul 12 2021 04:55:39 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Spencer_Lynch69",
          user_image: "https://cdn.fakercloud.com/avatars/bradenhamm_128.jpg",
        },
      },
      {
        order_id: "88350",
        order_title: "eligendi laudantium reiciendis",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://vern.com",
        order_price: "456.21",
        order_reward_price: "511.06",
        order_from: "Italy",
        order_to: "Cape Verde",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Thu Jan 07 2021 09:35:35 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Mallory.Batz38",
          user_image: "https://cdn.fakercloud.com/avatars/malykhinv_128.jpg",
        },
      },
      {
        order_id: "75279",
        order_title: "adipisci qui rerum",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://brendan.com",
        order_price: "936.07",
        order_reward_price: "878.69",
        order_from: "Venezuela",
        order_to: "Palestinian Territory",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Tue Aug 17 2021 01:19:32 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Mariana_Beer",
          user_image: "https://cdn.fakercloud.com/avatars/plasticine_128.jpg",
        },
      },
      {
        order_id: "60663",
        order_title: "impedit temporibus fugit",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://monserrate.com",
        order_price: "264.24",
        order_reward_price: "989.43",
        order_from: "Cambodia",
        order_to: "Syrian Arab Republic",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Sun Nov 21 2021 21:59:36 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Caroline43",
          user_image: "https://cdn.fakercloud.com/avatars/alterchuca_128.jpg",
        },
      },
      {
        order_id: "92858",
        order_title: "quasi suscipit modi",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://claudia.info",
        order_price: "451.13",
        order_reward_price: "409.16",
        order_from: "New Zealand",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_to: "Burundi",
        order_created_at: "Mon Oct 25 2021 00:57:01 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Florida.Smitham3",
          user_image: "https://cdn.fakercloud.com/avatars/dawidwu_128.jpg",
        },
      },
    ],
    posted_orders: [
      {
        order_id: "93195",
        order_title: "aspernatur nobis quidem",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://cleveland.info",
        order_price: "979.41",
        order_reward_price: "567.11",
        order_from: "Burkina Faso",
        order_to: "Belarus",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Mon Nov 15 2021 18:41:45 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Trisha_Walsh",
          user_image: "https://cdn.fakercloud.com/avatars/petrangr_128.jpg",
        },
      },
      {
        order_id: "25524",
        order_title: "nihil et quia",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://colleen.biz",
        order_price: "190.14",
        order_reward_price: "987.91",
        order_from: "Australia",
        order_to: "Niger",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Sat Aug 07 2021 17:12:45 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Josue.Senger55",
          user_image: "https://cdn.fakercloud.com/avatars/knilob_128.jpg",
        },
      },
      {
        order_id: "33651",
        order_title: "esse quam consequatur",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://abby.net",
        order_price: "875.60",
        order_reward_price: "65.80",
        order_from: "Malta",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_to: "Yemen",
        order_created_at: "Fri Jul 30 2021 19:35:57 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Garrison.Bartoletti",
          user_image: "https://cdn.fakercloud.com/avatars/harry_sistalam_128.jpg",
        },
      },
      {
        order_id: "85484",
        order_title: "ea enim eos",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://kenneth.biz",
        order_price: "860.48",
        order_reward_price: "424.11",
        order_from: "Saint Barthelemy",
        order_to: "Jersey",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Sat Jun 05 2021 09:12:20 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Skylar_Cummings",
          user_image: "https://cdn.fakercloud.com/avatars/manekenthe_128.jpg",
        },
      },
      {
        order_id: "37695",
        order_title: "illo accusamus eveniet",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://damien.org",
        order_price: "806.79",
        order_reward_price: "367.61",
        order_from: "Saint Helena",
        order_to: "Sweden",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Sat Jun 26 2021 06:38:27 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Juvenal_DuBuque46",
          user_image: "https://cdn.fakercloud.com/avatars/terryxlife_128.jpg",
        },
      },
    ],
    processing_orders: [
      {
        order_id: "49234",
        order_title: "fugiat nam quis",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://jacinthe.name",
        order_price: "273.15",
        order_reward_price: "245.65",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_from: "Antarctica (the territory South of 60 deg S)",
        order_to: "Northern Mariana Islands",
        order_created_at: "Sun Aug 22 2021 18:04:08 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Valentina.Lueilwitz",
          user_image: "https://cdn.fakercloud.com/avatars/dmitriychuta_128.jpg",
        },
        offer_by: {
          user_name: "Monte.Bauch12",
          user_image: "https://cdn.fakercloud.com/avatars/supervova_128.jpg",
        },
      },
      {
        order_id: "50167",
        order_title: "nesciunt ut dolorum",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://niko.biz",
        order_price: "240.82",
        order_reward_price: "258.56",
        order_from: "India",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_to: "Australia",
        order_created_at: "Tue May 25 2021 15:59:09 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Edna75",
          user_image: "https://cdn.fakercloud.com/avatars/id835559_128.jpg",
        },
        offer_by: {
          user_name: "Tatum_Parisian",
          user_image: "https://cdn.fakercloud.com/avatars/alecarpentier_128.jpg",
        },
      },
      {
        order_id: "58988",
        order_title: "neque ut aspernatur",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://emerald.net",
        order_price: "729.90",
        order_reward_price: "543.00",
        order_from: "Cyprus",
        order_to: "Iran",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Fri Oct 15 2021 18:38:30 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Kiana.Kirlin74",
          user_image: "https://cdn.fakercloud.com/avatars/victorerixon_128.jpg",
        },
        offer_by: {
          user_name: "Michael35",
          user_image: "https://cdn.fakercloud.com/avatars/gaborenton_128.jpg",
        },
      },
      {
        order_id: "68812",
        order_title: "dicta saepe rerum",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://richie.com",
        order_price: "791.94",
        order_reward_price: "486.99",
        order_from: "Trinidad and Tobago",
        order_to: "Romania",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Thu Dec 17 2020 22:48:44 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Allie18",
          user_image: "https://cdn.fakercloud.com/avatars/iamsteffen_128.jpg",
        },
        offer_by: {
          user_name: "Viva61",
          user_image: "https://cdn.fakercloud.com/avatars/djsherman_128.jpg",
        },
      },
      {
        order_id: "79486",
        order_title: "voluptas aut alias",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://leila.info",
        order_price: "271.67",
        order_reward_price: "741.13",
        order_from: "Somalia",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_to: "Netherlands Antilles",
        order_created_at: "Tue Mar 09 2021 00:00:13 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Nora6",
          user_image: "https://cdn.fakercloud.com/avatars/ryhanhassan_128.jpg",
        },
        offer_by: {
          user_name: "Raegan_Bartell54",
          user_image: "https://cdn.fakercloud.com/avatars/frankiefreesbie_128.jpg",
        },
      },
    ],
    delivered_orders: [
      {
        order_id: "12752",
        order_title: "ipsam quia ut",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://noemi.info",
        order_price: "503.69",
        order_reward_price: "657.14",
        order_from: "South Africa",
        order_to: "Brunei Darussalam",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Wed Oct 27 2021 13:21:11 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Brent.Funk",
          user_image: "https://cdn.fakercloud.com/avatars/dcalonaci_128.jpg",
        },
        offer_by: {
          user_name: "Zula47",
          user_image: "https://cdn.fakercloud.com/avatars/noxdzine_128.jpg",
        },
      },
      {
        order_id: "37320",
        order_title: "ipsa natus temporibus",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://lucie.biz",
        order_price: "793.94",
        order_reward_price: "335.82",
        order_from: "Kuwait",
        order_to: "Greenland",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Sun Aug 01 2021 11:44:15 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Cullen81",
          user_image: "https://cdn.fakercloud.com/avatars/nilshoenson_128.jpg",
        },
        offer_by: {
          user_name: "Bennett85",
          user_image: "https://cdn.fakercloud.com/avatars/felipeapiress_128.jpg",
        },
      },
      {
        order_id: "62431",
        order_title: "assumenda quia et",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://boris.biz",
        order_price: "822.43",
        order_reward_price: "1.82",
        order_from: "Venezuela",
        order_to: "Bahamas",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Fri Apr 30 2021 12:51:03 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Rogelio.Howe57",
          user_image: "https://cdn.fakercloud.com/avatars/cicerobr_128.jpg",
        },
        offer_by: {
          user_name: "Terence.Robel",
          user_image: "https://cdn.fakercloud.com/avatars/danvierich_128.jpg",
        },
      },
      {
        order_id: "23216",
        order_title: "eum sint veritatis",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://orlando.net",
        order_price: "605.64",
        order_reward_price: "265.63",
        order_from: "Dominican Republic",
        order_to: "Lao People's Democratic Republic",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Sat Jun 12 2021 18:58:43 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        order_by: {
          user_name: "Agustina.Walker",
          user_image: "https://cdn.fakercloud.com/avatars/bassamology_128.jpg",
        },
        offer_by: {
          user_name: "Ernestine_Tromp84",
          user_image: "https://cdn.fakercloud.com/avatars/adamnac_128.jpg",
        },
      },
      {
        order_id: "79228",
        order_title: "et pariatur natus",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://efren.net",
        order_price: "515.39",
        order_reward_price: "103.44",
        order_from: "Burkina Faso",
        order_to: "Timor-Leste",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Sun May 02 2021 10:50:43 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        order_by: {
          user_name: "Matilde30",
          user_image: "https://cdn.fakercloud.com/avatars/nvkznemo_128.jpg",
        },
        offer_by: {
          user_name: "Keven.Homenick",
          user_image: "https://cdn.fakercloud.com/avatars/mocabyte_128.jpg",
        },
      },
    ],
  },
};

const relevant_orders_list = {
  data: [
    {
      order_id: "55282",
      order_title: "sit facilis est",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://prince.name",
      order_price: "576.93",
      order_reward_price: "167.76",
      order_from: "Niger",
      order_to: "Poland",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Apr 18 2021 01:03:36 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Donna.Wiegand",
        user_image: "https://cdn.fakercloud.com/avatars/txcx_128.jpg",
      },
    },
    {
      order_id: "51487",
      order_title: "commodi dicta ut",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://flavio.info",
      order_price: "103.80",
      order_reward_price: "133.94",
      order_from: "Puerto Rico",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to: "Wallis and Futuna",
      order_created_at: "Sun Aug 29 2021 08:09:41 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Alexandre84",
        user_image: "https://cdn.fakercloud.com/avatars/knilob_128.jpg",
      },
    },
    {
      order_id: "61304",
      order_title: "minus maiores iste",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://misael.org",
      order_price: "738.00",
      order_reward_price: "488.17",
      order_from: "American Samoa",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to: "Belize",
      order_created_at: "Mon Nov 30 2020 07:08:21 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Leif84",
        user_image: "https://cdn.fakercloud.com/avatars/reabo101_128.jpg",
      },
    },
    {
      order_id: "36241",
      order_title: "debitis nihil debitis",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://jordan.biz",
      order_price: "314.91",
      order_reward_price: "378.36",
      order_from: "Estonia",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to: "French Southern Territories",
      order_created_at: "Tue Mar 09 2021 11:49:47 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Rosendo.Stamm",
        user_image: "https://cdn.fakercloud.com/avatars/gaborenton_128.jpg",
      },
    },
    {
      order_id: "68192",
      order_title: "minus esse ipsum",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://felipe.net",
      order_price: "264.88",
      order_reward_price: "964.02",
      order_from: "Costa Rica",
      order_to: "Uruguay",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Apr 16 2021 01:00:18 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Justice.Flatley",
        user_image: "https://cdn.fakercloud.com/avatars/mbilderbach_128.jpg",
      },
    },
    {
      order_id: "39440",
      order_title: "debitis tenetur sapiente",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://vena.net",
      order_price: "52.98",
      order_reward_price: "535.79",
      order_from: "Zimbabwe",
      order_to: "Grenada",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Apr 30 2021 16:27:58 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Ceasar_Kuhic99",
        user_image: "https://cdn.fakercloud.com/avatars/mufaddal_mw_128.jpg",
      },
    },
    {
      order_id: "68839",
      order_title: "sunt et facere",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://cordie.biz",
      order_price: "171.70",
      order_reward_price: "633.42",
      order_from: "Mali",
      order_to: "Cambodia",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Thu Oct 07 2021 07:43:01 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Ambrose.Osinski40",
        user_image: "https://cdn.fakercloud.com/avatars/nandini_m_128.jpg",
      },
    },
  ],
  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const posted_orders_list = {
  data: {
    local_orders: [
      {
        order_id: "95660",
        order_title: "sint enim et",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://jade.net",
        order_price: "160.72",
        order_reward_price: "624.68",
        order_from: "Slovenia",
        order_to: "Mayotte",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_created_at: "Sat Jan 09 2021 13:07:45 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        is_urgent: false,
        order_by: {
          user_name: "Kayli_Block88",
          user_image: "https://cdn.fakercloud.com/avatars/ryanjohnson_me_128.jpg",
        },
      },
      {
        order_id: "59036",
        order_title: "earum ab et",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://isadore.net",
        order_price: "315.07",
        order_reward_price: "295.98",
        order_from: "Rwanda",
        order_to: "Andorra",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_created_at: "Sun Aug 22 2021 00:35:08 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        is_urgent: false,
        order_by: {
          user_name: "Jeramy.Huels48",
          user_image: "https://cdn.fakercloud.com/avatars/dhrubo_128.jpg",
        },
      },
      {
        order_id: "44776",
        order_title: "labore atque reprehenderit",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://demond.org",
        order_price: "308.27",
        order_reward_price: "926.32",
        order_from: "French Southern Territories",
        order_to: "Malta",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_created_at: "Mon Jan 11 2021 22:22:21 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        is_urgent: false,
        order_by: {
          user_name: "Wilfrid_Towne68",
          user_image: "https://cdn.fakercloud.com/avatars/xtopherpaul_128.jpg",
        },
      },
      {
        order_id: "32405",
        order_title: "sint aut sit",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://lottie.net",
        order_price: "276.44",
        order_reward_price: "115.29",
        order_from: "Sao Tome and Principe",
        order_to: "Hungary",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_created_at: "Sat Mar 20 2021 10:17:13 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        is_urgent: true,
        order_by: {
          user_name: "Ruby41",
          user_image: "https://cdn.fakercloud.com/avatars/therealmarvin_128.jpg",
        },
      },
      {
        order_id: "78729",
        order_title: "animi illum et",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://christine.com",
        order_price: "24.74",
        order_reward_price: "473.68",
        order_from: "Qatar",
        order_to: "Republic of Korea",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_created_at: "Fri Feb 12 2021 01:12:56 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        is_urgent: true,
        order_by: {
          user_name: "Annie77",
          user_image: "https://cdn.fakercloud.com/avatars/tristanlegros_128.jpg",
        },
      },
    ],

    international_orders: [
      {
        order_id: "91950",
        order_title: "voluptates id facilis",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://reyes.name",
        order_price: "183.02",
        order_reward_price: "770.92",
        order_from: "French Polynesia",
        order_to: "Trinidad and Tobago",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Mon Jun 28 2021 12:04:34 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        is_urgent: false,
        order_by: {
          user_name: "Jackie_Crist",
          user_image: "https://cdn.fakercloud.com/avatars/SULiik_128.jpg",
        },
      },
      {
        order_id: "98571",
        order_title: "velit consequatur in",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://greyson.name",
        order_price: "834.31",
        order_reward_price: "454.41",
        order_from: "Jordan",
        order_to: "Pitcairn Islands",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Thu Dec 24 2020 10:29:32 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        is_urgent: true,
        order_by: {
          user_name: "Jany.Hane26",
          user_image: "https://cdn.fakercloud.com/avatars/sterlingrules_128.jpg",
        },
      },
      {
        order_id: "50228",
        order_title: "corrupti neque sunt",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://joanny.info",
        order_price: "198.22",
        order_reward_price: "505.45",
        order_from: "Costa Rica",
        order_to: "Cayman Islands",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Tue Aug 03 2021 06:22:55 GMT+0500 (Pakistan Standard Time)",
        is_international: false,
        is_urgent: true,
        order_by: {
          user_name: "Terence_Schaefer91",
          user_image: "https://cdn.fakercloud.com/avatars/gojeanyn_128.jpg",
        },
      },
      {
        order_id: "18952",
        order_title: "corrupti qui omnis",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://emery.net",
        order_price: "604.16",
        order_reward_price: "147.03",
        order_from: "Mexico",
        order_to: "Somalia",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Wed Nov 10 2021 04:06:45 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        is_urgent: true,
        order_by: {
          user_name: "Leonel_Price53",
          user_image: "https://cdn.fakercloud.com/avatars/richardgarretts_128.jpg",
        },
      },
      {
        order_id: "36664",
        order_title: "quidem laboriosam unde",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://francesca.org",
        order_price: "583.91",
        order_reward_price: "453.30",
        order_from: "Timor-Leste",
        order_to: "Lesotho",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        order_created_at: "Fri Sep 17 2021 19:49:13 GMT+0500 (Pakistan Standard Time)",
        is_international: true,
        is_urgent: false,
        order_by: {
          user_name: "Murl.Jenkins",
          user_image: "https://cdn.fakercloud.com/avatars/scottgallant_128.jpg",
        },
      },
    ],
  },
};

const processing_orders_list = {
  data: [
    {
      order_id: "11021",
      order_title: "quidem omnis mollitia",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://vella.name",
      order_price: "462.15",
      order_reward_price: "893.30",
      order_from: "Kiribati",
      order_to: "Burkina Faso",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Dec 09 2020 18:06:44 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Harrison26",
        user_image: "https://cdn.fakercloud.com/avatars/adamawesomeface_128.jpg",
      },
      offer_by: {
        user_name: "Lennie.Funk",
        user_image: "https://cdn.fakercloud.com/avatars/yigitpinarbasi_128.jpg",
      },
    },
    {
      order_id: "35434",
      order_title: "quis recusandae quia",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://amos.name",
      order_price: "169.97",
      order_reward_price: "592.39",
      order_from: "Mali",
      order_to: "Bangladesh",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Mar 27 2021 06:57:39 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Trace_Padberg",
        user_image: "https://cdn.fakercloud.com/avatars/franciscoamk_128.jpg",
      },
      offer_by: {
        user_name: "Eloise_Nitzsche4",
        user_image: "https://cdn.fakercloud.com/avatars/terpimost_128.jpg",
      },
    },
    {
      order_id: "19485",
      order_title: "id aliquam qui",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://coleman.org",
      order_price: "969.21",
      order_reward_price: "638.28",
      order_from: "Cayman Islands",
      order_to: "Russian Federation",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Thu Jul 22 2021 23:48:22 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Gage52",
        user_image: "https://cdn.fakercloud.com/avatars/justme_timothyg_128.jpg",
      },
      offer_by: {
        user_name: "Serenity_Kuhlman",
        user_image: "https://cdn.fakercloud.com/avatars/madewulf_128.jpg",
      },
    },
    {
      order_id: "33650",
      order_title: "ex voluptatibus corporis",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://kaley.info",
      order_price: "293.68",
      order_reward_price: "934.72",
      order_from: "Kazakhstan",
      order_to: "Liberia",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Jul 07 2021 16:10:23 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Flo_Boehm15",
        user_image: "https://cdn.fakercloud.com/avatars/simobenso_128.jpg",
      },
      offer_by: {
        user_name: "Zoe.Aufderhar",
        user_image: "https://cdn.fakercloud.com/avatars/dzantievm_128.jpg",
      },
    },
    {
      order_id: "24486",
      order_title: "non libero aperiam",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://hillary.net",
      order_price: "965.67",
      order_reward_price: "156.62",
      order_from: "Jersey",
      order_to: "Ireland",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Nov 13 2021 20:58:20 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Camron.Swaniawski",
        user_image: "https://cdn.fakercloud.com/avatars/anatolinicolae_128.jpg",
      },
      offer_by: {
        user_name: "Madie54",
        user_image: "https://cdn.fakercloud.com/avatars/hoangloi_128.jpg",
      },
    },
    {
      order_id: "82361",
      order_title: "rem voluptate veniam",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://hermina.info",
      order_price: "722.75",
      order_reward_price: "818.15",
      order_from: "Cayman Islands",
      order_to: "Virgin Islands, British",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Dec 19 2020 19:46:15 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Mary_Tromp",
        user_image: "https://cdn.fakercloud.com/avatars/surgeonist_128.jpg",
      },
      offer_by: {
        user_name: "Paula21",
        user_image: "https://cdn.fakercloud.com/avatars/mattlat_128.jpg",
      },
    },
    {
      order_id: "20363",
      order_title: "quae quaerat consectetur",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://ashton.org",
      order_price: "39.00",
      order_reward_price: "368.36",
      order_from: "Burkina Faso",
      order_to: "Egypt",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Feb 05 2021 19:18:31 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Jammie26",
        user_image: "https://cdn.fakercloud.com/avatars/danro_128.jpg",
      },
      offer_by: {
        user_name: "Hoyt15",
        user_image: "https://cdn.fakercloud.com/avatars/agromov_128.jpg",
      },
    },
  ],
  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const delivery_orders_list = {
  data: [
    {
      order_id: "46074",
      order_title: "autem earum voluptas",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://alyson.info",
      order_price: "851.30",
      order_reward_price: "331.72",
      order_from: "Albania",
      order_to: "Mozambique",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Jun 18 2021 11:03:07 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Marisa_Skiles",
        user_image: "https://cdn.fakercloud.com/avatars/adellecharles_128.jpg",
      },
      offer_by: {
        user_name: "Uriah60",
        user_image: "https://cdn.fakercloud.com/avatars/scott_riley_128.jpg",
      },
    },
    {
      order_id: "80895",
      order_title: "rerum facere nihil",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://kody.name",
      order_price: "90.88",
      order_reward_price: "99.09",
      order_from: "Burundi",
      order_to: "Portugal",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Aug 21 2021 00:42:09 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Hilton20",
        user_image: "https://cdn.fakercloud.com/avatars/ah_lice_128.jpg",
      },
      offer_by: {
        user_name: "Darrel_Hilll24",
        user_image: "https://cdn.fakercloud.com/avatars/kudretkeskin_128.jpg",
      },
    },
    {
      order_id: "30534",
      order_title: "dolor rerum et",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://vickie.com",
      order_price: "711.39",
      order_reward_price: "854.15",
      order_from: "Uganda",
      order_to: "Belize",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Mar 12 2021 21:18:35 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Coy.Lebsack",
        user_image: "https://cdn.fakercloud.com/avatars/heyimjuani_128.jpg",
      },
      offer_by: {
        user_name: "Tyler.Rau",
        user_image: "https://cdn.fakercloud.com/avatars/runningskull_128.jpg",
      },
    },
    {
      order_id: "48807",
      order_title: "et voluptatem odit",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://dale.net",
      order_price: "232.13",
      order_reward_price: "740.16",
      order_from: "Sierra Leone",
      order_to: "Cyprus",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Nov 28 2020 06:13:18 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Jacques.Ryan",
        user_image: "https://cdn.fakercloud.com/avatars/xilantra_128.jpg",
      },
      offer_by: {
        user_name: "Kevon48",
        user_image: "https://cdn.fakercloud.com/avatars/funwatercat_128.jpg",
      },
    },
    {
      order_id: "50478",
      order_title: "et molestias illum",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://alberta.biz",
      order_price: "201.93",
      order_reward_price: "458.07",
      order_from: "Denmark",
      order_to: "Turkmenistan",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Apr 02 2021 21:19:46 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      order_by: {
        user_name: "Walker28",
        user_image: "https://cdn.fakercloud.com/avatars/edobene_128.jpg",
      },
      offer_by: {
        user_name: "Isabelle16",
        user_image: "https://cdn.fakercloud.com/avatars/picard102_128.jpg",
      },
    },
    {
      order_id: "65714",
      order_title: "illo ad id",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://tyree.info",
      order_price: "231.15",
      order_reward_price: "200.54",
      order_from: "Latvia",
      order_to: "Guernsey",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Jan 13 2021 02:39:42 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Merle.Buckridge14",
        user_image: "https://cdn.fakercloud.com/avatars/supjoey_128.jpg",
      },
      offer_by: {
        user_name: "Leanne_Koss3",
        user_image: "https://cdn.fakercloud.com/avatars/sta1ex_128.jpg",
      },
    },
    {
      order_id: "50532",
      order_title: "a et impedit",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://madaline.info",
      order_price: "822.59",
      order_reward_price: "126.97",
      order_from: "Angola",
      order_to: "Yemen",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri May 14 2021 16:47:36 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      order_by: {
        user_name: "Quinn_Schuppe86",
        user_image: "https://cdn.fakercloud.com/avatars/jay_wilburn_128.jpg",
      },
      offer_by: {
        user_name: "Christopher.Price",
        user_image: "https://cdn.fakercloud.com/avatars/kazaky999_128.jpg",
      },
    },
  ],
  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const make_single_offer = {
  data: {
    order_id: "57812",
    order_title: "et adipisci quidem",
    order_image: "http://placeimg.com/640/480",
    order_store_url: "https://callie.name",
    order_price: "301.64",
    order_reward_price: "968.36",
    order_deliver_before: "Fri Dec 31 2021 15:49:47 GMT+0500 (Pakistan Standard Time)",
    order_quantity: "3",
    order_packaging: true,
    order_from: "El Salvador",
    order_to: "Iceland",
    order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
    order_created_at: "Tue Jul 20 2021 23:05:16 GMT+0500 (Pakistan Standard Time)",
    is_international: true,
    is_urgent: true,
    urgent_delivery: [
      {
        urgent_delivery_id: "28513",
        urgent_delivery_content: "24 hours delivery",
        urgent_delivery_reward: "111.19",
      },
      {
        urgent_delivery_id: "23296",
        urgent_delivery_content: "2 days delivery",
        urgent_delivery_reward: "672.22",
      },
      {
        urgent_delivery_id: "32089",
        urgent_delivery_content: "3 days delivery",
        urgent_delivery_reward: "281.88",
      },
    ],
    order_by: {
      user_name: "Nat67",
      user_image: "https://cdn.fakercloud.com/avatars/craigrcoles_128.jpg",
    },
  },
};

const singleCompletedOrderDetails = {
  data: {
    order_id: "95235",
    order_title: "esse quia sunt",
    order_image: "http://placeimg.com/640/480",
    order_store_url: "http://tyra.biz",
    order_price: "146.70",
    order_reward_price: "961.04",
    order_deliver_before: "Thu Aug 11 2022 16:07:51 GMT+0500 (Pakistan Standard Time)",
    order_quantity: "3",
    order_packaging: true,
    order_from: "Libyan Arab Jamahiriya",
    order_to: "Macedonia",
    order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
    order_created_at: "Wed May 05 2021 14:50:43 GMT+0500 (Pakistan Standard Time)",
    is_international: false,
    is_urgent: true,

    order_by: {
      user_name: "Jolie39",
      user_image: "https://cdn.fakercloud.com/avatars/alexivanichkin_128.jpg",
    },
  },
};

const postedLocalOrderList = {
  data: [
    {
      order_id: "35318",
      order_title: "perferendis velit blanditiis",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://jade.info",
      order_price: "233.06",
      order_reward_price: "952.96",
      order_from: "Macedonia",
      order_to: "Seychelles",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Apr 11 2021 10:40:58 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_by: {
        user_name: "Cindy.Stracke28",
        user_image: "https://cdn.fakercloud.com/avatars/omnizya_128.jpg",
      },
    },
    {
      order_id: "56264",
      order_title: "voluptate quis nesciunt",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://prudence.info",
      order_price: "179.36",
      order_reward_price: "455.96",
      order_from: "Kazakhstan",
      order_to: "Aruba",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Aug 20 2021 01:27:38 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_by: {
        user_name: "Nellie_McGlynn57",
        user_image: "https://cdn.fakercloud.com/avatars/buddhasource_128.jpg",
      },
    },
    {
      order_id: "75117",
      order_title: "qui accusamus vitae",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://concepcion.biz",
      order_price: "778.49",
      order_reward_price: "437.14",
      order_from: "Pakistan",
      order_to: "Nepal",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Jul 18 2021 06:38:57 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: true,
      order_by: {
        user_name: "Javonte97",
        user_image: "https://cdn.fakercloud.com/avatars/elisabethkjaer_128.jpg",
      },
    },
    {
      order_id: "48000",
      order_title: "velit rerum quibusdam",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://marina.org",
      order_price: "431.56",
      order_reward_price: "303.48",
      order_from: "Zimbabwe",
      order_to: "Saint Kitts and Nevis",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Mar 07 2021 02:24:28 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_by: {
        user_name: "Sammy.Kreiger64",
        user_image: "https://cdn.fakercloud.com/avatars/markolschesky_128.jpg",
      },
    },
    {
      order_id: "38243",
      order_title: "libero doloribus quisquam",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://edwardo.com",
      order_price: "317.56",
      order_reward_price: "523.71",
      order_from: "Iran",
      order_to: "Zimbabwe",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Tue Jan 05 2021 18:18:32 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_by: {
        user_name: "Johnson14",
        user_image: "https://cdn.fakercloud.com/avatars/alessandroribe_128.jpg",
      },
    },
    {
      order_id: "32485",
      order_title: "ad quia laboriosam",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://marilou.info",
      order_price: "208.33",
      order_reward_price: "976.97",
      order_from: "Austria",
      order_to: "Honduras",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Jul 30 2021 18:12:10 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_by: {
        user_name: "Shad_Metz75",
        user_image: "https://cdn.fakercloud.com/avatars/xadhix_128.jpg",
      },
    },
    {
      order_id: "30916",
      order_title: "et dolores harum",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://crawford.biz",
      order_price: "206.72",
      order_reward_price: "521.76",
      order_from: "Kuwait",
      order_to: "Cameroon",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Mar 21 2021 04:49:33 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: true,
      order_by: {
        user_name: "Marcelino_Nikolaus76",
        user_image: "https://cdn.fakercloud.com/avatars/heycamtaylor_128.jpg",
      },
    },
  ],
  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const postedInternationalOrderList = {
  data: {
    highest_paid_destinations: [
      {
        destination: "UK - London",
        total_orders: "968 Orders",
        destination_landmark: "http://placeimg.com/640/480",
        total_rewards: "US$ 10,500",
      },

      {
        destination: "USA - California",
        total_orders: "786 Orders",
        destination_landmark: "http://placeimg.com/640/480",
        total_rewards: "US$ 8,790",
      },
      {
        destination: "Lebnon - Beirut",
        total_orders: "356 Orders",
        destination_landmark: "http://placeimg.com/640/480",
        total_rewards: "US$ 5,879",
      },
    ],

    international_orders: [
      {
        order_id: "41367",
        order_title: "quia accusantium distinctio",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://hermina.com",
        order_price: "345.90",
        order_reward_price: "481.57",
        order_from: "Democratic People's Republic of Korea",
        order_to: "Somalia",
        order_created_at: "Sat Apr 24 2021 13:31:12 GMT+0500 (Pakistan Standard Time)",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        is_international: true,
        is_urgent: true,
        order_by: {
          user_name: "Lula_Bernhard35",
          user_image: "https://cdn.fakercloud.com/avatars/enricocicconi_128.jpg",
        },
      },
      {
        order_id: "42890",
        order_title: "rem ipsa sequi",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "https://zechariah.info",
        order_price: "667.69",
        order_reward_price: "347.58",
        order_from: "British Indian Ocean Territory (Chagos Archipelago)",
        order_to: "Azerbaijan",
        order_created_at: "Sat Aug 21 2021 11:29:24 GMT+0500 (Pakistan Standard Time)",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        is_international: true,
        is_urgent: false,
        order_by: {
          user_name: "Georgette.Koepp53",
          user_image: "https://cdn.fakercloud.com/avatars/moscoz_128.jpg",
        },
      },
      {
        order_id: "86514",
        order_title: "commodi possimus et",
        order_image: "http://placeimg.com/640/480",
        order_store_url: "http://jerrold.net",
        order_price: "920.11",
        order_reward_price: "315.04",
        order_from: "Jordan",
        order_to: "Malaysia",
        order_created_at: "Sun Nov 07 2021 12:36:58 GMT+0500 (Pakistan Standard Time)",
        order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
        order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
        is_international: true,
        is_urgent: false,
        order_by: {
          user_name: "Clement_Schamberger",
          user_image: "https://cdn.fakercloud.com/avatars/agromov_128.jpg",
        },
      },
    ],
  },
};

const displayAllInternationalOrdersList = {
  data: [
    {
      order_id: "55642",
      order_title: "qui perspiciatis est",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://harmony.biz",
      order_price: "102.79",
      order_reward_price: "294.49",
      order_from: "Tokelau",
      order_to: "Congo",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Nov 13 2021 07:05:11 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_by: {
        user_name: "Karianne.Bergstrom41",
        user_image: "https://cdn.fakercloud.com/avatars/travishines_128.jpg",
      },
    },
    {
      order_id: "23532",
      order_title: "at libero saepe",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://gregg.name",
      order_price: "946.83",
      order_reward_price: "940.57",
      order_from: "Central African Republic",
      order_to: "Wallis and Futuna",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Tue Dec 01 2020 15:13:39 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_by: {
        user_name: "Susana_Veum",
        user_image: "https://cdn.fakercloud.com/avatars/cggaurav_128.jpg",
      },
    },
    {
      order_id: "79391",
      order_title: "nisi sunt voluptate",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://abby.name",
      order_price: "348.15",
      order_reward_price: "102.65",
      order_from: "Algeria",
      order_to: "Tuvalu",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Tue Feb 23 2021 03:26:50 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_by: {
        user_name: "Cary.Rutherford",
        user_image: "https://cdn.fakercloud.com/avatars/rmlewisuk_128.jpg",
      },
    },
    {
      order_id: "59619",
      order_title: "eius vel sunt",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://nikko.net",
      order_price: "20.38",
      order_reward_price: "274.50",
      order_from: "Botswana",
      order_to: "Tanzania",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Thu May 06 2021 12:49:47 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_by: {
        user_name: "Isom.Hamill27",
        user_image: "https://cdn.fakercloud.com/avatars/_ragzor_128.jpg",
      },
    },
    {
      order_id: "88791",
      order_title: "excepturi ut ut",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://barney.name",
      order_price: "909.04",
      order_reward_price: "314.84",
      order_from: "Taiwan",
      order_to: "Australia",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Oct 10 2021 22:24:15 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_by: {
        user_name: "Eudora_Kris72",
        user_image: "https://cdn.fakercloud.com/avatars/idiot_128.jpg",
      },
    },
    {
      order_id: "85490",
      order_title: "voluptas quis similique",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://alf.com",
      order_price: "875.91",
      order_reward_price: "655.95",
      order_from: "Tokelau",
      order_to: "Solomon Islands",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Thu Oct 07 2021 01:13:10 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_by: {
        user_name: "Brionna91",
        user_image: "https://cdn.fakercloud.com/avatars/abdullindenis_128.jpg",
      },
    },
    {
      order_id: "47807",
      order_title: "unde beatae architecto",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://pink.biz",
      order_price: "320.47",
      order_reward_price: "757.42",
      order_from: "Niue",
      order_to: "Greece",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Mon Jan 25 2021 18:53:55 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_by: {
        user_name: "Dawn_Bashirian36",
        user_image: "https://cdn.fakercloud.com/avatars/franciscoamk_128.jpg",
      },
    },
    {
      order_id: "72810",
      order_title: "laudantium sapiente voluptates",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://isaiah.name",
      order_price: "271.08",
      order_reward_price: "84.64",
      order_from: "Ukraine",
      order_to: "Congo",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Sep 19 2021 00:32:33 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_by: {
        user_name: "Chasity_Rosenbaum",
        user_image: "https://cdn.fakercloud.com/avatars/anthonysukow_128.jpg",
      },
    },
    {
      order_id: "60438",
      order_title: "debitis et dolor",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://elvis.info",
      order_price: "874.55",
      order_reward_price: "712.72",
      order_from: "Zambia",
      order_to: "Netherlands",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Oct 15 2021 20:14:06 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_by: {
        user_name: "Golda31",
        user_image: "https://cdn.fakercloud.com/avatars/nfedoroff_128.jpg",
      },
    },
    {
      order_id: "98454",
      order_title: "labore soluta repellendus",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://agustin.info",
      order_price: "811.41",
      order_reward_price: "297.53",
      order_from: "Mauritius",
      order_to: "Turkey",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Aug 01 2021 08:21:15 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: true,
      order_by: {
        user_name: "Erling.Friesen",
        user_image: "https://cdn.fakercloud.com/avatars/loganjlambert_128.jpg",
      },
    },
  ],
  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 10,
      count: 10,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const orderOffersRequestsList = {
  data: {
    order_id: "65515",
    order_title: "maxime autem tempore",
    order_image: "http://placeimg.com/640/480",
    order_store_url: "http://fern.name",
    order_price: "940.67",
    order_reward_price: "586.57",
    order_deliver_before: "Mon May 02 2022 03:04:03 GMT+0500 (Pakistan Standard Time)",
    order_quantity: "1",
    order_packaging: true,
    order_from: "South Africa",
    order_to: "French Polynesia",
    order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
    order_created_at: "Mon Sep 20 2021 09:18:13 GMT+0500 (Pakistan Standard Time)",
    is_international: false,
    is_urgent: true,
    offers_list: [
      {
        offer_id: "46838",
        offer_by: "Skylar_Auer34",
        user_image: "https://cdn.fakercloud.com/avatars/pierre_nel_128.jpg",
        offer_reward: "776.92",
        offer_delivery_on: "Tue Feb 08 2022 17:44:23 GMT+0500 (Pakistan Standard Time)",
        offer_status: "pending",
      },
      {
        offer_id: "63843",
        offer_by: "Clifton.Hirthe85",
        user_image: "https://cdn.fakercloud.com/avatars/benefritz_128.jpg",
        offer_reward: "970.88",
        offer_delivery_on: "Sat Nov 12 2022 20:33:19 GMT+0500 (Pakistan Standard Time)",
        offer_status: "pending",
      },
      {
        offer_id: "82722",
        offer_by: "Jarod7",
        user_image: "https://cdn.fakercloud.com/avatars/thedamianhdez_128.jpg",
        offer_reward: "966.99",
        offer_delivery_on: "Sat Oct 15 2022 15:30:30 GMT+0500 (Pakistan Standard Time)",
        offer_status: "rejected",
      },
    ],
  },
};

const offerDetails = {
  data: {
    order_id: "69912",
    order_title: "dolore dolore quibusdam",
    order_image: "http://placeimg.com/640/480",
    order_store_url: "https://marian.name",
    order_price: "746.19",
    order_reward_price: "531.62",
    order_deliver_before: "Tue Feb 01 2022 13:12:27 GMT+0500 (Pakistan Standard Time)",
    order_quantity: "4",
    order_instruction: "Consequatur voluptatum facilis enim.",
    order_packaging: true,
    order_from: "Togo",
    order_to: "Lesotho",
    order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
    order_created_at: "Mon Nov 08 2021 16:56:10 GMT+0500 (Pakistan Standard Time)",
    is_international: true,
    is_urgent: true,
    offer_id: "35641",
    offer_by_id: "71146",
    offer_by: "Tamia.OHara87",
    offer_reward: "164.63",
    offer_delivery_on: "Sun Jan 02 2022 09:41:41 GMT+0500 (Pakistan Standard Time)",
  },
};

const internationalHistoryOrder = {
  data: [
    {
      order_id: "10705",
      order_title: "provident eum fuga",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://liliane.name",
      order_price: "181.70",
      order_reward_price: "61.82",
      order_deliver_before: "Sun Mar 20 2022 15:50:14 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "1",
      order_packaging: true,
      order_from: "Seychelles",
      order_to: "Trinidad and Tobago",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Sep 25 2021 14:45:08 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
    {
      order_id: "56715",
      order_title: "quibusdam dolores ut",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://hermann.net",
      order_price: "332.98",
      order_reward_price: "358.55",
      order_deliver_before: "Mon Dec 27 2021 08:06:18 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "3",
      order_packaging: true,
      order_from: "Saudi Arabia",
      order_to: "Morocco",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Sep 19 2021 21:59:33 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_status: "Address Requested",
      order_next_step: "Delivery Address Requested",
    },
    {
      order_id: "85461",
      order_title: "assumenda sit voluptas",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://amy.biz",
      order_price: "525.25",
      order_reward_price: "947.33",
      order_deliver_before: "Thu Sep 08 2022 11:35:55 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "1",
      order_packaging: true,
      order_from: "Jersey",
      order_to: "Gambia",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Jan 09 2021 17:58:56 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
    {
      order_id: "54456",
      order_title: "aut rerum perspiciatis",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://luz.com",
      order_price: "815.07",
      order_reward_price: "203.22",
      order_deliver_before: "Thu Aug 18 2022 13:14:11 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "5",
      order_packaging: true,
      order_from: "Palau",
      order_to: "Mozambique",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Tue Sep 07 2021 21:16:29 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
    {
      order_id: "87571",
      order_title: "libero illum nihil",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://genoveva.org",
      order_price: "90.38",
      order_reward_price: "723.36",
      order_deliver_before: "Wed Nov 24 2021 19:20:03 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "1",
      order_packaging: true,
      order_from: "France",
      order_to: "Burkina Faso",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Sep 22 2021 08:57:54 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
  ],

  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const localHistoryOrder = {
  data: [
    {
      order_id: "21447",
      order_title: "ut rerum ut",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://timmy.com",
      order_price: "741.95",
      order_reward_price: "816.39",
      order_deliver_before: "Tue Jul 05 2022 10:26:32 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "5",
      order_packaging: true,
      order_from: "Kyrgyz Republic",
      order_to: "Nigeria",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Mon Sep 13 2021 02:34:55 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "96726",
      order_title: "consequatur voluptates id",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://humberto.net",
      order_price: "34.25",
      order_reward_price: "198.94",
      order_deliver_before: "Wed Dec 01 2021 12:31:23 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "2",
      order_packaging: true,
      order_from: "Bouvet Island (Bouvetoya)",
      order_to: "Guinea",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sat Apr 24 2021 08:11:36 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "90734",
      order_title: "aliquid possimus dolore",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://queen.com",
      order_price: "267.96",
      order_reward_price: "894.90",
      order_deliver_before: "Fri Apr 22 2022 08:40:31 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "5",
      order_packaging: true,
      order_from: "Guadeloupe",
      order_to: "Luxembourg",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri May 07 2021 21:33:24 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "27736",
      order_title: "beatae iure enim",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://justine.name",
      order_price: "424.80",
      order_reward_price: "996.31",
      order_deliver_before: "Sat Dec 04 2021 13:06:57 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "5",
      order_packaging: true,
      order_from: "Germany",
      order_to: "Dominica",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Feb 24 2021 23:17:42 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "30941",
      order_title: "non eligendi et",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://halie.name",
      order_price: "310.22",
      order_reward_price: "338.47",
      order_deliver_before: "Sat Dec 18 2021 13:55:52 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "4",
      order_packaging: true,
      order_from: "Serbia",
      order_to: "Maldives",
      order_from_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Apr 07 2021 14:02:17 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
  ],

  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const internationalOrderDeliveryHistory = {
  data: [
    {
      order_id: "83993",
      order_title: "ad ut rerum",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://hermann.net",
      order_price: "663.84",
      order_reward_price: "835.08",
      order_deliver_before: "Sun Oct 16 2022 19:23:49 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "2",
      order_packaging: true,
      order_from: "Myanmar",
      order_to: "United Arab Emirates",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Thu Dec 24 2020 19:58:28 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "79612",
      order_title: "ut accusamus aut",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://breanna.info",
      order_price: "326.62",
      order_reward_price: "280.58",
      order_deliver_before: "Sun Mar 06 2022 07:43:27 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "3",
      order_packaging: true,
      order_from: "Antarctica (the territory South of 60 deg S)",
      order_to: "United Kingdom",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Oct 15 2021 18:01:00 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "40601",
      order_title: "quaerat consequuntur tenetur",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://erika.name",
      order_price: "307.56",
      order_reward_price: "439.10",
      order_deliver_before: "Sat Nov 27 2021 11:39:30 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "5",
      order_packaging: true,
      order_from: "Tajikistan",
      order_to: "Saint Pierre and Miquelon",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Sun Aug 22 2021 01:59:26 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "26598",
      order_title: "quos reiciendis ut",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://edd.net",
      order_price: "738.63",
      order_reward_price: "741.41",
      order_deliver_before: "Sat Dec 11 2021 20:00:04 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "4",
      order_packaging: true,
      order_from: "Dominica",
      order_to: "Macao",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Fri Dec 18 2020 16:40:20 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },

    {
      order_id: "67500",
      order_title: "voluptatem laboriosam consequatur",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://vince.com",
      order_price: "814.07",
      order_reward_price: "415.42",
      order_deliver_before: "Thu Nov 17 2022 23:38:46 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "2",
      order_packaging: true,
      order_from: "Finland",
      order_to: "Portugal",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Aug 04 2021 04:00:45 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
  ],

  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const localOrderDeliveryHistory = {
  data: [
    {
      order_id: "92006",
      order_title: "voluptatem eum tempore",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://ara.name",
      order_price: "481.59",
      order_reward_price: "253.86",
      order_deliver_before: "Thu Apr 21 2022 20:57:39 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "4",
      order_packaging: true,
      order_from: "Burundi",
      order_to: "Bouvet Island (Bouvetoya)",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_created_at: "Sun Dec 20 2020 02:32:10 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
    {
      order_id: "84480",
      order_title: "culpa nostrum mollitia",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://joshuah.info",
      order_price: "985.38",
      order_reward_price: "988.02",
      order_deliver_before: "Tue Nov 15 2022 17:42:11 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "3",
      order_packaging: true,
      order_from: "Latvia",
      order_to: "Ghana",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_created_at: "Thu Nov 11 2021 04:07:06 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
    {
      order_id: "20378",
      order_title: "maxime voluptatem ut",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://sheila.info",
      order_price: "125.73",
      order_reward_price: "618.59",
      order_deliver_before: "Sun Jul 03 2022 18:05:27 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "5",
      order_packaging: true,
      order_from: "Guadeloupe",
      order_to: "Senegal",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_created_at: "Fri Sep 03 2021 13:21:35 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
    {
      order_id: "23206",
      order_title: "fuga sed incidunt",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://ervin.biz",
      order_price: "798.66",
      order_reward_price: "425.92",
      order_deliver_before: "Thu Nov 03 2022 15:20:30 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "5",
      order_packaging: true,
      order_from: "Libyan Arab Jamahiriya",
      order_to: "Lesotho",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_created_at: "Sun Sep 26 2021 00:57:15 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
    {
      order_id: "70996",
      order_title: "id aut expedita",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://alize.org",
      order_price: "40.41",
      order_reward_price: "279.87",
      order_deliver_before: "Mon Jan 10 2022 03:33:37 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "1",
      order_packaging: true,
      order_from: "Germany",
      order_to: "Jamaica",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_created_at: "Fri Aug 06 2021 02:24:55 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Pending Reward Approval",
    },
  ],

  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const disputedOrderList = {
  data: [
    {
      order_id: "24052",
      order_title: "voluptas qui qui",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "http://iliana.net",
      order_price: "996.77",
      order_reward_price: "993.66",
      order_deliver_before: "Mon May 23 2022 21:50:59 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "2",
      order_packaging: true,
      order_from: "United Arab Emirates",
      order_to: "Kiribati",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Thu Sep 16 2021 00:52:11 GMT+0500 (Pakistan Standard Time)",
      is_international: false,
      is_urgent: false,
      order_status: "Pending Reward",
      order_next_step: "Disputed Receipt",
    },

    {
      order_id: "28282",
      order_title: "voluptatibus natus quo",
      order_image: "http://placeimg.com/640/480",
      order_store_url: "https://rowena.org",
      order_price: "743.28",
      order_reward_price: "691.06",
      order_deliver_before: "Wed Oct 12 2022 08:10:15 GMT+0500 (Pakistan Standard Time)",
      order_quantity: "2",
      order_packaging: true,
      order_from: "Poland",
      order_to: "Austria",
      order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
      order_to_flag: "https://www.worldometers.info/img/flags/ku-flag.gif",
      order_created_at: "Wed Oct 27 2021 09:54:09 GMT+0500 (Pakistan Standard Time)",
      is_international: true,
      is_urgent: true,
      order_status: "Approved Reward",
      order_next_step: "Disputed Delivery",
    },
  ],
  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const signleDeliveryHistoryOrderDetails = {
  data:{
    "order_id":"70933",
    "order_title": "voluptatibus et vitae",
    "order_image":"http://placeimg.com/640/480",
    "order_store_url":  "https://paige.biz",
    "order_reward_price":"89.91",
    "order_final_reward_price":"102.72",
    "order_total_price":"828.74",
    "order_deliver_before":"Thu Oct 20 2022 17:10:24 GMT+0500 (Pakistan Standard Time)",
    "order_quantity":"3",
    "order_instructions":"Atque necessitatibus laborum autem quia.",
    "order_packaging": true,
   
    "order_by":
    {
      "user_id":"47843",
      "user_name":"Monty86",
      "user_image":"https://cdn.fakercloud.com/avatars/kinday_128.jpg", 
    
    },
  }
};

const popularStoresList = {
  data: {
    "Top Stores": [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://marquis.biz",
      },
    ],

    consequatur: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "https://isabella.biz",
      },
    ],

    magnam: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://oscar.com",
      },
    ],

    velit: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://modesta.net",
      },
    ],

    dolorum: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://zelma.info",
      },
    ],

    ut: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "https://eunice.biz",
      },
    ],

    iusto: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://milton.info",
      },
    ],

    sint: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "https://kendall.biz",
      },
    ],

    voluptas: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://aron.name",
      },
    ],

    facere: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://nikolas.info",
      },
    ],

    non: [
      {
        store_image: "http://placeimg.com/640/480",
        store_url: "http://loraine.org",
      },
    ],
  },
};

const walletHistoryList = {
  data: [
    {
      type: "Invitation",
      trip: "N-A",
      order_id: "N-A",
      trn_date: "Wed May 05 2021 23:11:28 GMT+0500 (Pakistan Standard Time)",
      is_credit: true,
      total: "523.28",
    },

    {
      type: "Delivery",
      trip: "KW - KW",
      order_id: "60756",
      trn_date: "Wed Jun 30 2021 03:38:23 GMT+0500 (Pakistan Standard Time)",
      is_credit: true,
      total: "21.55",
    },

    {
      type: "Refund",
      trip: "Kw - USA",
      order_id: "21591",
      trn_date: "Thu Oct 14 2021 09:43:27 GMT+0500 (Pakistan Standard Time)",
      is_credit: true,
      total: "929.14",
    },

    {
      type: "Top-Up",
      trip: "N-A",
      order_id: "N-A",
      trn_date: "Mon Sep 13 2021 16:17:48 GMT+0500 (Pakistan Standard Time)",
      is_credit: true,
      total: "989.31",
    },

    {
      type: "Cashout",
      trip: "N-A",
      order_id: "N-A",
      trn_date: "Sun Jan 10 2021 01:00:34 GMT+0500 (Pakistan Standard Time)",
      is_credit: false,
      total: "42.40",
    },

    {
      type: "Payout",
      trip: "KW - KW",
      order_id: "93151",
      trn_date: "Wed Jun 23 2021 16:39:28 GMT+0500 (Pakistan Standard Time)",
      is_credit: false,
      total: "411.33",
    },
  ],

  meta: {
    include: [],
    custom: [],
    pagination: {
      total: 7,
      count: 7,
      per_page: 10,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

const walletDeliveryOrderDetails = {
  data: {
    order_id: "43497",
    order_title: "omnis qui nihil",
    order_image: "http://placeimg.com/640/480",
    order_store_url: "http://monserrat.org",
    order_price: "710.14",
    order_reward_price: "363.55",
    order_deliver_before: "Tue Apr 05 2022 11:22:09 GMT+0500 (Pakistan Standard Time)",
    order_quantity: "5",
    order_packaging: true,
    order_from: "El Salvador",
    order_to: "Liberia",
    order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_created_at: "Fri Mar 05 2021 08:21:59 GMT+0500 (Pakistan Standard Time)",
    is_international: false,
    is_urgent: true,
    rewarded_price: "660.38",
    delivered_on: "Wed Jun 23 2021 10:27:35 GMT+0500 (Pakistan Standard Time)",
    order_by: {
      user_name: "Catherine_Steuber42",
      user_image: "https://cdn.fakercloud.com/avatars/to_soham_128.jpg",
    },
    offer_by: {
      user_name: "Daphne_VonRueden79",
      user_image: "https://cdn.fakercloud.com/avatars/terrorpixel_128.jpg",
    },
  },
};

const walletPayoutOrderDetails = {
  data: {
    order_id: "75480",
    order_title: "quae ut ducimus",
    order_image: "http://placeimg.com/640/480",
    order_store_url: "http://jalon.info",
    order_price: "752.28",
    order_reward_price: "490.50",
    order_deliver_before: "Wed Dec 29 2021 20:09:33 GMT+0500 (Pakistan Standard Time)",
    order_quantity: "2",
    order_packaging: true,
    order_from: "Montenegro",
    order_to: "Moldova",
    order_from_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_to_flag: "https://www.worldometers.info/img/flags/ae-flag.gif",
    order_created_at: "Fri Jan 15 2021 19:16:47 GMT+0500 (Pakistan Standard Time)",
    is_international: true,
    is_urgent: false,
    delivered_on: "Fri Dec 04 2020 16:43:19 GMT+0500 (Pakistan Standard Time)",
    "taketo fee": "917.45",
    payment_processing: "927.55",
    payout: "821.26",
    payment_method: "Taketo Wallet",
    taxes: [
      {
        tax_name: "US SaleTax",
        tax_amount: "32.99",
      },
    ],
    order_by: {
      user_name: "Julie_Larkin33",
      user_image: "https://cdn.fakercloud.com/avatars/rdbannon_128.jpg",
    },

    offer_by: {
      user_name: "Francisco.Lynch67",
      user_image: "https://cdn.fakercloud.com/avatars/ovall_128.jpg",
    },
  },
};

const walletRefundOrderDetails = {
  data: {
    order_id: "31563",
    order_title: "debitis ipsa quam",
    order_image: "http://placeimg.com/640/480",
    order_store_url: "https://webster.name",
    order_price: "402.84",
    order_reward_price: "479.54",
    order_deliver_before: "Wed Mar 30 2022 23:10:43 GMT+0500 (Pakistan Standard Time)",
    order_quantity: "3",
    order_packaging: true,
    order_from: "Sao Tome and Principe",
    order_to: "San Marino",
    order_created_at: "Fri Sep 24 2021 10:13:30 GMT+0500 (Pakistan Standard Time)",
    is_international: false,
    is_urgent: true,
    refunded_price: "410.68",
    failed_on: "Thu Mar 11 2021 09:30:06 GMT+0500 (Pakistan Standard Time)",
    failed_reason: "Buyer no show",
    order_by: {
      user_name: "Tyler_Muller",
      user_image: "https://cdn.fakercloud.com/avatars/vaughanmoffitt_128.jpg",
    },
    offer_by: {
      user_name: "Mekhi_Prohaska",
      user_image: "https://cdn.fakercloud.com/avatars/aiiaiiaii_128.jpg",
    },
  },
};

const TAKE_TO_MOCK = {
  onBoardContentList, //integrated
  conversation, //integrated
  home_orders_list, //integrated
  relevant_orders_list, //integrated
  posted_orders_list, //integrated
  processing_orders_list, //integrated
  delivery_orders_list, //integrated
  make_single_offer, //integrated
  singleCompletedOrderDetails,
  postedLocalOrderList, //integrated
  postedInternationalOrderList, //integrated
  displayAllInternationalOrdersList, //integrated
  orderOffersRequestsList, //integrated
  offerDetails, //integrated
  internationalHistoryOrder, //integrared
  localHistoryOrder, //integrared
  internationalOrderDeliveryHistory, //integrated
  localOrderDeliveryHistory, //integrated
  disputedOrderList, //integrated
  signleDeliveryHistoryOrderDetails,//Integrated
  popularStoresList, //integrated
  walletHistoryList, //integrated
  walletDeliveryOrderDetails, //integrated
  walletRefundOrderDetails, //integrated
  walletPayoutOrderDetails, //integrated
};

export default TAKE_TO_MOCK;
